site_name: MeteoNet's Documentation
theme:
  name: 'material'
  icon:
    logo: 'material/cloud'
  features:
    - tabs
repo_url: https://github.com/meteofrance/meteonet
repo_name: 'GitHub'

docs_dir: 'docs_src'
site_dir: 'docs'

plugins:
  - search
  - mkdocs-add-number-plugin:
      strict_mode: False
      order: 2
  - awesome-pages

markdown_extensions:
  - footnotes
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - admonition
  - attr_list
  - mdx_math

extra_javascript: 
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

nav:
  - English:
    - 'index.md'
    - 'english/getting-started.md'
    - 'english/install.md'
    - Data:
      - 'english/data/summary.md'
      - 'english/data/ground-observations.md'
      - 'english/data/rain-radar.md'
      - 'english/data/weather-models.md'
      - 'english/data/satellite.md'
      - 'english/data/land-relief-masks.md'
    - 'english/glossary.md'
    - 'english/help.md'
  - Français:
    - 'french/accueil.md'
    - 'french/commencer.md'
    - 'french/installation.md'
    - Données:
      - 'french/donnees/resume.md'
      - 'french/donnees/stations-observation.md'
      - 'french/donnees/radar-pluie.md'
      - 'french/donnees/modeles-meteo.md'
      - 'french/donnees/masques-terre-relief.md'
    - 'french/glossaire.md'
    - 'french/aide.md'
  
